import type {Metadata} from "next";

import {CopilotKit} from "@copilotkit/react-core";

import "./globals.css";

import "@copilotkit/react-ui/styles.css";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
  }: Readonly<{
    children: React.ReactNode;
  }>) {
    // Step 4: Return the JSX structure for the layout
    return (
      <html lang="en">
        <body className={"antialiased"}>
          {/* Step 5: Wrap the children components with CopilotKit provider to enable CopilotKit functionality */}
          <CopilotKit runtimeUrl="/api/copilotkit" agent="default">
            {children}
          </CopilotKit>
        </body>
      </html>
    );
  }